<?php
// database/seeders/ProductSeeder.php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run()
    {
        // Get category IDs
        $categories = Category::all()->keyBy('slug');

        $products = [
            // TUBES DE PRELEVEMENT (Category ID: tubes-de-prelevement)
            [
                'name' => 'Tube PRP GEL+NC1:9',
                'slug' => 'tube-prp-gelnc19',
                'sku' => 'PRP-GEL-001',
                'price' => 140.00,
                'original_price' => 150.00,
                'category_slug' => 'tubes-de-prelevement',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/whatsapp-image-2026-01-21-at-140953-photoroom-300x300.png',
                'description' => 'Tube PRP jetable avec ACD+GEL. La cellulose, la fibronectine et la vitronectine contenues dans le PRP peuvent transformer le PRP contenant de la thrombine en gel. Le PRP peut favoriser la régénération osseuse, augmenter la densité osseuse et favoriser la cicatrisation des plaies.',
                'features' => json_encode([
                    'Tube PRP stérile, à usage unique',
                    'Diamètre: 15mm, bouchon: 18mm',
                    'Modèle 10ml: jusqu\'à 9ml de sang',
                    'Modèle 15ml: jusqu\'à 12ml de sang',
                    'Certifié CE classe IIa'
                ]),
                'attributes' => json_encode([
                    'condition' => ['Unité', 'Boîte/100'],
                    'color' => ['BLUE', 'GREEN'],
                    'size' => ['10ML', '15ML']
                ]),
                'stock' => 45,
                'rating' => 4.5,
                'reviews_count' => 12,
                'badge' => 'Hot',
                'featured' => true,
            ],
            [
                'name' => 'Tube Sous Vide ESR 1,6ml en Verre',
                'slug' => 'tube-sous-vide-esr',
                'sku' => 'ESR-GLASS-001',
                'price' => 120.00,
                'original_price' => null,
                'category_slug' => 'tubes-de-prelevement',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/gemini-generated-image-b4on7wb4on7wb4on-300x300.jpg',
                'description' => 'Tube sous vide pour vitesse de sédimentation (ESR) en verre de haute qualité. Idéal pour les tests de laboratoire précis.',
                'features' => null,
                'attributes' => null,
                'stock' => 38,
                'rating' => 4.2,
                'reviews_count' => 8,
                'badge' => 'Hot',
                'featured' => true,
            ],
            [
                'name' => 'Tube Sous Vide Fluoré De Potassium En Plastique',
                'slug' => 'tube-sous-vide-floure-potassium',
                'sku' => 'FLUOR-PLASTIC-001',
                'price' => 130.00,
                'original_price' => null,
                'category_slug' => 'tubes-de-prelevement',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-202209012048532-600x-300x300.jpg',
                'description' => 'Tube sous vide avec fluorure de potassium pour la stabilisation du glucose. En plastique de haute qualité.',
                'features' => null,
                'attributes' => null,
                'stock' => 52,
                'rating' => 4.7,
                'reviews_count' => 15,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide avec Gel Séparateur En Plastique',
                'slug' => 'tube-sous-vide-gel-separateur',
                'sku' => 'GEL-PLASTIC-001',
                'price' => 140.00,
                'original_price' => null,
                'category_slug' => 'tubes-de-prelevement',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-202209012048541-2a25-300x300.jpg',
                'description' => 'Tube sous vide avec gel séparateur pour une séparation optimale du sérum. En plastique de haute qualité.',
                'features' => null,
                'attributes' => null,
                'stock' => 27,
                'rating' => 4.3,
                'reviews_count' => 10,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide Héparine En Plastique',
                'slug' => 'tube-sous-vide-heparine',
                'sku' => 'HEPARINE-PLASTIC-001',
                'price' => 125.00,
                'original_price' => null,
                'category_slug' => 'tubes-de-prelevement',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-20220901204853-1200x-300x300.jpg',
                'description' => 'Tube sous vide avec héparine de lithium pour les tests de chimie clinique. En plastique de haute qualité.',
                'features' => null,
                'attributes' => null,
                'stock' => 63,
                'rating' => 4.6,
                'reviews_count' => 14,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide Citrate pour V.S En Plastique',
                'slug' => 'tube-sous-vide-citrate-vs',
                'sku' => 'CITRATE-VS-PLASTIC-001',
                'price' => 135.00,
                'original_price' => null,
                'category_slug' => 'tubes-de-prelevement',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/whatsapp-image-2026-01-21-at-140429-1-photoroom-300x300.png',
                'description' => 'Tube sous vide avec citrate de sodium pour la vitesse de sédimentation. En plastique de haute qualité.',
                'features' => null,
                'attributes' => null,
                'stock' => 41,
                'rating' => 4.4,
                'reviews_count' => 9,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide Citrate pour Coagulation En Plastique',
                'slug' => 'tube-sous-vide-citrate-coagulation',
                'sku' => 'CITRATE-COAG-PLASTIC-001',
                'price' => 138.00,
                'original_price' => null,
                'category_slug' => 'tubes-de-prelevement',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-20220901204854-1024x-300x300.jpg',
                'description' => 'Tube sous vide avec citrate de sodium pour les tests de coagulation. En plastique de haute qualité.',
                'features' => null,
                'attributes' => null,
                'stock' => 35,
                'rating' => 4.5,
                'reviews_count' => 11,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide EDTA En Plastique',
                'slug' => 'tube-sous-vide-edta',
                'sku' => 'EDTA-PLASTIC-001',
                'price' => 125.00,
                'original_price' => null,
                'category_slug' => 'tubes-de-prelevement',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/65309-home-default-300x300.jpg',
                'description' => 'Tube sous vide avec EDTA pour les analyses hématologiques. En plastique de haute qualité.',
                'features' => null,
                'attributes' => null,
                'stock' => 58,
                'rating' => 4.6,
                'reviews_count' => 13,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide SEC (Avec Activateur) En Plastique',
                'slug' => 'tube-sous-vide-sec',
                'sku' => 'SEC-PLASTIC-001',
                'price' => 132.00,
                'original_price' => null,
                'category_slug' => 'tubes-de-prelevement',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-202209012048531-1200x-300x300.webp',
                'description' => 'Tube sous vide avec activateur de coagulation pour les tests biochimiques. En plastique de haute qualité.',
                'features' => null,
                'attributes' => null,
                'stock' => 42,
                'rating' => 4.4,
                'reviews_count' => 9,
                'badge' => 'Hot',
                'featured' => false,
            ],

            // AIGUILLES ET ACCESSOIRES
            [
                'name' => 'Tampon Alcoolisé',
                'slug' => 'tampon-alcoolise',
                'sku' => 'TAMPON-001',
                'price' => 45.00,
                'original_price' => null,
                'category_slug' => 'aiguilles-et-accessoires',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/aiguilles/whatsapp-image-2026-01-22-at-115900-300x300.jpeg',
                'description' => 'Tampons alcoolisés individuels pour la désinfection de la peau avant prélèvement. Format pratique et stérile.',
                'features' => null,
                'attributes' => null,
                'stock' => 200,
                'rating' => 4.1,
                'reviews_count' => 6,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Garrot avec crochet pour Adulte',
                'slug' => 'garrot-avec-crochet-pour-adulte',
                'sku' => 'GARROT-001',
                'price' => 65.00,
                'original_price' => null,
                'category_slug' => 'aiguilles-et-accessoires',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/aiguilles/whatsapp-image-2026-01-22-at-115548-300x300.jpeg',
                'description' => 'Garrot professionnel avec système de crochet pour un maintien facile. Conçu pour adultes, réglable et confortable.',
                'features' => null,
                'attributes' => null,
                'stock' => 85,
                'rating' => 4.3,
                'reviews_count' => 7,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Corps avec dispositif d\'éjection d\'aiguille',
                'slug' => 'corps-avec-dispositif-dejection-daiguille',
                'sku' => 'CORPS-EJECT-001',
                'price' => 85.00,
                'original_price' => null,
                'category_slug' => 'aiguilles-et-accessoires',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/aiguilles/whatsapp-image-2026-01-22-at-115425-300x300.jpeg',
                'description' => 'Corps de prélèvement avec système d\'éjection d\'aiguille intégré pour une sécurité optimale.',
                'features' => null,
                'attributes' => null,
                'stock' => 42,
                'rating' => 4.5,
                'reviews_count' => 11,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Corps pour Aiguille',
                'slug' => 'corps-pour-aiguille',
                'sku' => 'CORPS-001',
                'price' => 55.00,
                'original_price' => null,
                'category_slug' => 'aiguilles-et-accessoires',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/aiguilles/whatsapp-image-2026-01-22-at-115222-300x300.jpeg',
                'description' => 'Corps de prélèvement standard compatible avec la plupart des aiguilles de prélèvement.',
                'features' => null,
                'attributes' => null,
                'stock' => 97,
                'rating' => 4.2,
                'reviews_count' => 5,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Aiguille épicrânienne',
                'slug' => 'aiguille-epicranienne',
                'sku' => 'AIGUILLE-EPI-001',
                'price' => 38.00,
                'original_price' => null,
                'category_slug' => 'aiguilles-et-accessoires',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/aiguilles/whatsapp-image-2026-01-22-at-120743-300x300.jpeg',
                'description' => 'Aiguille épicrânienne pour prélèvements spécifiques. Stérile et à usage unique.',
                'features' => null,
                'attributes' => null,
                'stock' => 75,
                'rating' => 4.3,
                'reviews_count' => 6,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Aiguille Hypodermique 25Gx1',
                'slug' => 'aiguille-hypodermique-25gx1',
                'sku' => 'AIGUILLE-HYPO-25G',
                'price' => 35.00,
                'original_price' => null,
                'category_slug' => 'aiguilles-et-accessoires',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/aiguilles/whatsapp-image-2026-01-22-at-115703-300x300.jpeg',
                'description' => 'Aiguille hypodermique stérile 25G x 1 pouce. Pour injections et prélèvements. Emballage individuel.',
                'features' => null,
                'attributes' => null,
                'stock' => 150,
                'rating' => 4.4,
                'reviews_count' => 8,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Aiguille avec vision 22G1',
                'slug' => 'aiguille-avec-vision-22g1',
                'sku' => 'AIGUILLE-VISION-22G',
                'price' => 42.00,
                'original_price' => null,
                'category_slug' => 'aiguilles-et-accessoires',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/aiguilles/whatsapp-image-2026-01-22-at-114911-1-300x300.jpeg',
                'description' => 'Aiguille avec chambre de vision pour un contrôle optimal du flux sanguin. 22G, stérile.',
                'features' => null,
                'attributes' => null,
                'stock' => 62,
                'rating' => 4.6,
                'reviews_count' => 9,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Aiguille sous vide 21G1',
                'slug' => 'aiguille-sous-vide-21g1',
                'sku' => 'AIGUILLE-SV-21G',
                'price' => 40.00,
                'original_price' => null,
                'category_slug' => 'aiguilles-et-accessoires',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/aiguilles/whatsapp-image-2026-01-21-at-165605-300x300.jpeg',
                'description' => 'Aiguille sous vide standard 21G pour prélèvement sanguin. Compatible avec tous les tubes sous vide.',
                'features' => null,
                'attributes' => null,
                'stock' => 120,
                'rating' => 4.5,
                'reviews_count' => 10,
                'badge' => null,
                'featured' => false,
            ],

            // CONSOMMABLES DE LABORATOIRE
            [
                'name' => 'Sparadrap CURE-AID',
                'slug' => 'sparadrap-cure-aid',
                'sku' => 'SPARADRAP-001',
                'price' => 150.00,
                'original_price' => 200.00,
                'category_slug' => 'consommables-de-laboratoire',
                'brand' => 'Cure-Aid',
                'image' => 'https://teclab.ma/storage/products/chatgpt-image-feb-26-2026-02-01-23-pm-300x300.png',
                'description' => 'Sparadrap hypoallergénique pour fixation de pansements et compresses. Haute adhérence et doux pour la peau.',
                'features' => null,
                'attributes' => null,
                'stock' => 75,
                'rating' => 4.4,
                'reviews_count' => 18,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'RACK/cône Blanc 96 Trous',
                'slug' => 'rackcone-blanc-96-trous',
                'sku' => 'RACK-96-001',
                'price' => 95.00,
                'original_price' => null,
                'category_slug' => 'consommables-de-laboratoire',
                'brand' => 'Labware',
                'image' => 'https://teclab.ma/storage/products/aiguilles/chatgpt-image-feb-24-2026-02-31-01-pm-300x300.png',
                'description' => 'Rack pour cônes de pipettes, 96 trous. Compatible avec la plupart des pipettes automatiques. Blanc, résistant.',
                'features' => null,
                'attributes' => null,
                'stock' => 30,
                'rating' => 4.2,
                'reviews_count' => 7,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Ecouvillon stérile tige en bois',
                'slug' => 'ecouvillon-sterile-tige-en-bois',
                'sku' => 'ECOUVILLON-001',
                'price' => 75.00,
                'original_price' => null,
                'category_slug' => 'consommables-de-laboratoire',
                'brand' => 'Carestainer',
                'image' => 'https://teclab.ma/storage/products/eccouvillons/gemini-generated-image-dp8g8idp8g8idp8g-300x300.jpg',
                'description' => 'Ecouvillon stérile avec tige en bois pour prélèvements microbiologiques. Emballage individuel.',
                'features' => null,
                'attributes' => null,
                'stock' => 200,
                'rating' => 4.3,
                'reviews_count' => 9,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'CUPULE ACCESS 2 BEKMAN COULTER',
                'slug' => 'cupule-access-2-bekman-coulter',
                'sku' => 'CUPULE-ACCESS-001',
                'price' => 180.00,
                'original_price' => null,
                'category_slug' => 'cuvettes-cupules-flacons-de-billes',
                'brand' => 'Beckman Coulter',
                'image' => 'https://teclab.ma/storage/products/autre/chatgpt-image-feb-24-2026-01-32-00-pm-300x300.png',
                'description' => 'Cupule pour analyseur ACCESS 2 de Beckman Coulter. Qualité garantie, compatible avec l\'équipement d\'origine.',
                'features' => null,
                'attributes' => null,
                'stock' => 120,
                'rating' => 4.5,
                'reviews_count' => 12,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'CUVETTE HITACHI',
                'slug' => 'cuvette-hitachi',
                'sku' => 'CUVETTE-HITACHI-001',
                'price' => 220.00,
                'original_price' => null,
                'category_slug' => 'cuvettes-cupules-flacons-de-billes',
                'brand' => 'Hitachi',
                'image' => 'https://teclab.ma/storage/products/cupule-godet/gemini-generated-image-2gfnvt2gfnvt2gfn-300x300.jpg',
                'description' => 'Cuvette pour analyseurs Hitachi, haute qualité optique. Précision et fiabilité pour vos analyses.',
                'features' => null,
                'attributes' => null,
                'stock' => 85,
                'rating' => 4.7,
                'reviews_count' => 8,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'CUVETTE KONELAB',
                'slug' => 'cuvette-konelab',
                'sku' => 'CUVETTE-KONELAB-001',
                'price' => 210.00,
                'original_price' => null,
                'category_slug' => 'cuvettes-cupules-flacons-de-billes',
                'brand' => 'Konelab',
                'image' => 'https://teclab.ma/storage/products/cupule-godet/gemini-generated-image-k4t0klk4t0klk4t0-300x300.jpg',
                'description' => 'Cuvette pour analyseurs Konelab, précision et fiabilité. Haute qualité optique.',
                'features' => null,
                'attributes' => null,
                'stock' => 64,
                'rating' => 4.6,
                'reviews_count' => 7,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'FLACON DE BILLE STAGO',
                'slug' => 'flacon-de-bille-stago',
                'sku' => 'FLACON-STAGO-001',
                'price' => 195.00,
                'original_price' => null,
                'category_slug' => 'cuvettes-cupules-flacons-de-billes',
                'brand' => 'Stago',
                'image' => 'https://teclab.ma/storage/products/cupule-godet/gemini-generated-image-evfpdyevfpdyevfp-300x300.png',
                'description' => 'Flacon de billes pour analyseurs Stago, qualité garantie. Pour tests de coagulation précis.',
                'features' => null,
                'attributes' => null,
                'stock' => 45,
                'rating' => 4.8,
                'reviews_count' => 5,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'CUVETTE STAGO',
                'slug' => 'cuvette-stago',
                'sku' => 'CUVETTE-STAGO-001',
                'price' => 185.00,
                'original_price' => null,
                'category_slug' => 'cuvettes-cupules-flacons-de-billes',
                'brand' => 'Stago',
                'image' => 'https://teclab.ma/storage/products/cupule-godet/gemini-generated-image-4dbarv4dbarv4dba-300x300.jpg',
                'description' => 'Cuvette pour analyseurs Stago, qualité optique optimale. Pour résultats fiables.',
                'features' => null,
                'attributes' => null,
                'stock' => 52,
                'rating' => 4.5,
                'reviews_count' => 6,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'CUPULE pour SYSMEX CS',
                'slug' => 'cupule-pour-sysmex-cs',
                'sku' => 'CUPULE-SYSMEX-CS-001',
                'price' => 175.00,
                'original_price' => null,
                'category_slug' => 'cuvettes-cupules-flacons-de-billes',
                'brand' => 'Sysmex',
                'image' => 'https://teclab.ma/storage/products/cupule-godet/gemini-generated-image-91dpm491dpm491dp-300x300.jpg',
                'description' => 'Cupule pour analyseur SYSMEX CS, précision garantie. Compatible avec l\'équipement d\'origine.',
                'features' => null,
                'attributes' => null,
                'stock' => 38,
                'rating' => 4.7,
                'reviews_count' => 4,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'CUPULE pour SYSMEX CA',
                'slug' => 'cupule-pour-sysmex-ca',
                'sku' => 'CUPULE-SYSMEX-CA-001',
                'price' => 170.00,
                'original_price' => null,
                'category_slug' => 'cuvettes-cupules-flacons-de-billes',
                'brand' => 'Sysmex',
                'image' => 'https://teclab.ma/storage/products/cupule-godet/gemini-generated-image-qmaokxqmaokxqmao-300x300.jpg',
                'description' => 'Cupule pour analyseur SYSMEX CA, qualité supérieure. Pour des résultats précis et fiables.',
                'features' => null,
                'attributes' => null,
                'stock' => 42,
                'rating' => 4.6,
                'reviews_count' => 5,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'CUPULE pour AUTOMATE A15 et A25',
                'slug' => 'cupule-pour-automate-a15-et-a25',
                'sku' => 'CUPULE-A15-A25-001',
                'price' => 155.00,
                'original_price' => null,
                'category_slug' => 'cuvettes-cupules-flacons-de-billes',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/products/cupule-godet/gemini-generated-image-ypliy4ypliy4ypli-300x300.jpg',
                'description' => 'Cupule pour automates A15 et A25, compatible avec Bioelab. Qualité garantie.',
                'features' => null,
                'attributes' => null,
                'stock' => 56,
                'rating' => 4.4,
                'reviews_count' => 7,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Micropipette Fixe 10 μl',
                'slug' => 'micropipette-fixe-10-ml',
                'sku' => 'MICROPIPETTE-FIXE-001',
                'price' => 450.00,
                'original_price' => null,
                'category_slug' => 'micropipettes',
                'brand' => 'Labware',
                'image' => 'https://teclab.ma/storage/products/micropipettes/gemini-generated-image-l3thb9l3thb9l3th-300x300.jpg',
                'description' => 'Micropipette à volume fixe, précision et ergonomie. Idéale pour les laboratoires exigeants.',
                'features' => null,
                'attributes' => null,
                'stock' => 25,
                'rating' => 4.8,
                'reviews_count' => 10,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Micropipette Réglable',
                'slug' => 'micropipette-reglable',
                'sku' => 'MICROPIPETTE-REG-001',
                'price' => 580.00,
                'original_price' => null,
                'category_slug' => 'micropipettes',
                'brand' => 'Labware',
                'image' => 'https://teclab.ma/storage/products/micropipettes/gemini-generated-image-vpzim5vpzim5vpzi-300x300.jpg',
                'description' => 'Micropipette à volume réglable, haute précision. Ergonomique et fiable pour tous vos besoins.',
                'features' => null,
                'attributes' => null,
                'stock' => 18,
                'rating' => 4.9,
                'reviews_count' => 8,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Parafilm 10cm*38m',
                'slug' => 'parafilm-10cm38m',
                'sku' => 'PARAFILM-001',
                'price' => 220.00,
                'original_price' => null,
                'category_slug' => 'consommables-de-laboratoire',
                'brand' => 'Parafilm',
                'image' => 'https://teclab.ma/storage/products/divers/gemini-generated-image-ltg7n2ltg7n2ltg7-300x300.jpg',
                'description' => 'Parafilm pour l\'étanchéité des récipients de laboratoire. Flexible, imperméable et facile à utiliser.',
                'features' => null,
                'attributes' => null,
                'stock' => 45,
                'rating' => 4.7,
                'reviews_count' => 12,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Pince en bois',
                'slug' => 'pince-en-bois',
                'sku' => 'PINCE-BOIS-001',
                'price' => 25.00,
                'original_price' => null,
                'category_slug' => 'consommables-de-laboratoire',
                'brand' => 'Labware',
                'image' => 'https://teclab.ma/storage/products/divers/gemini-generated-image-nt2q37nt2q37nt2q-300x300.jpg',
                'description' => 'Pince en bois pour la manipulation d\'objets chauds ou stériles. Usage unique, économique.',
                'features' => null,
                'attributes' => null,
                'stock' => 150,
                'rating' => 4.2,
                'reviews_count' => 15,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Micropipette multicanaux 0.5 à 10 μl',
                'slug' => 'micropipette-multicanaux-05-a-10-ml',
                'sku' => 'MICROPIPETTE-MULTI-001',
                'price' => 890.00,
                'original_price' => null,
                'category_slug' => 'micropipettes',
                'brand' => 'Labware',
                'image' => 'https://teclab.ma/storage/products/micropipettes/gemini-generated-image-vedalrvedalrveda-300x300.jpg',
                'description' => 'Micropipette multicanaux 8 canaux pour plaques 96 puits. Précision et rapidité pour vos séries d\'analyses.',
                'features' => null,
                'attributes' => null,
                'stock' => 8,
                'rating' => 4.9,
                'reviews_count' => 4,
                'badge' => null,
                'featured' => true,
            ],

            // ANALYSEURS
            [
                'name' => 'Analyseur de biochimie BT-330',
                'slug' => 'bioelab-bt-330',
                'sku' => 'ANALYSEUR-BT330',
                'price' => 15000.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-de-biochimie',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/products/machine/chatgpt-image-feb-14-2026-12-09-48-pm-300x300.png',
                'description' => 'Analyseur de biochimie entièrement automatisé. Haute précision et rapidité. Idéal pour les laboratoires modernes.',
                'features' => null,
                'attributes' => null,
                'stock' => 5,
                'rating' => 4.8,
                'reviews_count' => 3,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'ANALYSEUR POUR VITESSE DE SEDIMENTATION SD-100',
                'slug' => 'succeeder-sd-100',
                'sku' => 'ANALYSEUR-SD100',
                'price' => 12000.00,
                'original_price' => null,
                'category_slug' => 'analyseur-vitesse-sedimentation',
                'brand' => 'Succeeder',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-eim67heim67heim6-300x300.png',
                'description' => 'Analyseur pour vitesse de sédimentation, automatisé et précis. Résultats rapides et fiables.',
                'features' => null,
                'attributes' => null,
                'stock' => 3,
                'rating' => 4.6,
                'reviews_count' => 2,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur de biochimie AS-380',
                'slug' => 'bioelab-as-380',
                'sku' => 'ANALYSEUR-AS380',
                'price' => 18000.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-de-biochimie',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-h7hvj8h7hvj8h7hv-300x300.png',
                'description' => 'Analyseur de biochimie haute performance avec grande capacité. Idéal pour les laboratoires à fort volume.',
                'features' => null,
                'attributes' => null,
                'stock' => 2,
                'rating' => 4.9,
                'reviews_count' => 4,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Analyseur de biochimie AS-280',
                'slug' => 'bioelab-as-280',
                'sku' => 'ANALYSEUR-AS280',
                'price' => 14500.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-de-biochimie',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/products/machine/3406e3f080cff89509270b153c5605af-300x300.png',
                'description' => 'Analyseur de biochimie compact et efficace. Parfait pour les petits et moyens laboratoires.',
                'features' => null,
                'attributes' => null,
                'stock' => 4,
                'rating' => 4.7,
                'reviews_count' => 3,
                'badge' => 'Hot',
                'featured' => true,
            ],
            [
                'name' => 'Analyseur d\'hématologie BH-5390',
                'slug' => 'urit-bh-5390',
                'sku' => 'ANALYSEUR-BH5390',
                'price' => 22000.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-dhematologie',
                'brand' => 'Urit',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-yew64uyew64uyew6-300x300.png',
                'description' => 'Analyseur d\'hématologie 5-part avec automate complet. Haute précision et rapidité.',
                'features' => null,
                'attributes' => null,
                'stock' => 2,
                'rating' => 4.8,
                'reviews_count' => 2,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Analyseur d\'hématologie BH-5100',
                'slug' => 'urit-bh-5100',
                'sku' => 'ANALYSEUR-BH5100',
                'price' => 25000.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-dhematologie',
                'brand' => 'Urit',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-ah1r0rah1r0rah1r-300x300.png',
                'description' => 'Analyseur d\'hématologie haute capacité. Idéal pour les laboratoires à fort volume d\'analyses.',
                'features' => null,
                'attributes' => null,
                'stock' => 1,
                'rating' => 4.9,
                'reviews_count' => 1,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Analyseur de coagulation entièrement automatisé SF-8100',
                'slug' => 'succeeder-sf-8100',
                'sku' => 'ANALYSEUR-SF8100',
                'price' => 28000.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-de-coagulation',
                'brand' => 'Succeeder',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-vitlwbvitlwbvitl-300x300.png',
                'description' => 'Analyseur de coagulation entièrement automatisé. Précision et fiabilité pour vos tests de coagulation.',
                'features' => null,
                'attributes' => null,
                'stock' => 2,
                'rating' => 4.8,
                'reviews_count' => 2,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Analyseur de coagulation semi-automatique SF-8050',
                'slug' => 'succeeder-sf-8050',
                'sku' => 'ANALYSEUR-SF8050',
                'price' => 16500.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-de-coagulation',
                'brand' => 'Succeeder',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-pvfxm2pvfxm2pvfx-300x300.png',
                'description' => 'Analyseur de coagulation semi-automatique. Idéal pour les petits laboratoires.',
                'features' => null,
                'attributes' => null,
                'stock' => 3,
                'rating' => 4.6,
                'reviews_count' => 2,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Semi automated coagulation analyzer SF-400',
                'slug' => 'succeeder-sf-400',
                'sku' => 'ANALYSEUR-SF400',
                'price' => 12500.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-de-coagulation',
                'brand' => 'Succeeder',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-jmxae8jmxae8jmxa-300x300.png',
                'description' => 'Analyseur de coagulation semi-automatique compact. Simple d\'utilisation et fiable.',
                'features' => null,
                'attributes' => null,
                'stock' => 4,
                'rating' => 4.5,
                'reviews_count' => 3,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur d\'hémoglobine glyquée MQ-6000',
                'slug' => 'medconn-mq-6000',
                'sku' => 'ANALYSEUR-MQ6000',
                'price' => 19500.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-dhemoglobine-glycquee',
                'brand' => 'Medconn',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-hz7r96hz7r96hz7r-300x300.png',
                'description' => 'Analyseur d\'hémoglobine glyquée haute précision. Résultats rapides pour le suivi du diabète.',
                'features' => null,
                'attributes' => null,
                'stock' => 3,
                'rating' => 4.7,
                'reviews_count' => 2,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Analyseur d\'hémoglobine glyquée MQ-2000PT',
                'slug' => 'medconn-mq-2000pt',
                'sku' => 'ANALYSEUR-MQ2000PT',
                'price' => 16800.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-dhemoglobine-glycquee',
                'brand' => 'Medconn',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-uih99zuih99zuih9-300x300.png',
                'description' => 'Analyseur d\'hémoglobine glyquée avec technologie avancée. Précis et facile à utiliser.',
                'features' => null,
                'attributes' => null,
                'stock' => 4,
                'rating' => 4.6,
                'reviews_count' => 2,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur d\'hémoglobine glyquée MQ-3000',
                'slug' => 'medconn-mq-3000',
                'sku' => 'ANALYSEUR-MQ3000',
                'price' => 17800.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-dhemoglobine-glycquee',
                'brand' => 'Medconn',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-iqmn91iqmn91iqmn-300x300.png',
                'description' => 'Analyseur d\'hémoglobine glyquée avec automate. Parfait pour les laboratoires de taille moyenne.',
                'features' => null,
                'attributes' => null,
                'stock' => 3,
                'rating' => 4.7,
                'reviews_count' => 2,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur Hurricane Immunoassay System HIPRO',
                'slug' => 'hipro-hurricane',
                'sku' => 'ANALYSEUR-HURRICANE',
                'price' => 32000.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-de-biochimie',
                'brand' => 'HIPRO',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-82gnve82gnve82gn-300x300.png',
                'description' => 'Analyseur Hurricane Immunoassay System, haute performance pour analyses immunologiques.',
                'features' => null,
                'attributes' => null,
                'stock' => 1,
                'rating' => 5.0,
                'reviews_count' => 1,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Analyseur immunologique HP-AFS/A1 PLUS HIPRO',
                'slug' => 'hipro-a1-plus',
                'sku' => 'ANALYSEUR-HP-AFS',
                'price' => 28500.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-de-biochimie',
                'brand' => 'HIPRO',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-8mjsuh8mjsuh8mjs-300x300.png',
                'description' => 'Analyseur immunologique haute sensibilité. Pour analyses spécialisées.',
                'features' => null,
                'attributes' => null,
                'stock' => 2,
                'rating' => 4.8,
                'reviews_count' => 1,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Analyseur de gaz du sang EG-i',
                'slug' => 'eaglenos-serie-eg-i',
                'sku' => 'ANALYSEUR-EGI',
                'price' => 22500.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-de-gaz-du-sang',
                'brand' => 'Eaglenos',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-39ijah39ijah39ij-300x300.png',
                'description' => 'Analyseur de gaz du sang, rapide et précis. Idéal pour les services d\'urgence.',
                'features' => null,
                'attributes' => null,
                'stock' => 2,
                'rating' => 4.7,
                'reviews_count' => 2,
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Electrolyte Analyzer EAGLENOS (K+;Na+;Cl-;iCa2+;iMg2+) EG-P1',
                'slug' => 'eaglenos-serie-eg-p1',
                'sku' => 'ANALYSEUR-EGP1',
                'price' => 19800.00,
                'original_price' => null,
                'category_slug' => 'analyseurs-delectrolytes',
                'brand' => 'Eaglenos',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-552llq552llq552l-300x300.png',
                'description' => 'Analyseur d\'électrolytes (K+, Na+, Cl-, iCa2+, iMg2+). Précis et fiable pour vos analyses.',
                'features' => null,
                'attributes' => null,
                'stock' => 3,
                'rating' => 4.6,
                'reviews_count' => 2,
                'badge' => null,
                'featured' => true,
            ],

            // REACTIFS DE LABORATOIRE
            [
                'name' => 'VANCOMYCINE VA-5',
                'slug' => 'vancomycine-va-5',
                'sku' => 'REACTIF-VA5',
                'price' => 250.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Vancomycine 5μg pour tests de sensibilité. Boîte de 50 disques.',
                'features' => null,
                'attributes' => null,
                'stock' => 60,
                'rating' => 4.5,
                'reviews_count' => 5,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'VANCOMYCINE VA-30',
                'slug' => 'vancomycine-va-30',
                'sku' => 'REACTIF-VA30',
                'price' => 280.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Vancomycine 30μg pour tests de sensibilité. Boîte de 50 disques.',
                'features' => null,
                'attributes' => null,
                'stock' => 55,
                'rating' => 4.6,
                'reviews_count' => 4,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'TOBRAMYCINE TOB-10',
                'slug' => 'tobramycine-tob-10',
                'sku' => 'REACTIF-TOB10',
                'price' => 220.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Tobramycine 10μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 48,
                'rating' => 4.4,
                'reviews_count' => 3,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'TICARCILLINE TIC-75',
                'slug' => 'ticarcilline-tic-75',
                'sku' => 'REACTIF-TIC75',
                'price' => 265.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Ticarcilline 75μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 42,
                'rating' => 4.5,
                'reviews_count' => 3,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'TETRACYCLINE TE-30',
                'slug' => 'tetracycline-te-30',
                'sku' => 'REACTIF-TE30',
                'price' => 190.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Tétracycline 30μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 65,
                'rating' => 4.3,
                'reviews_count' => 6,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'TEICOPLANINE TEC-30',
                'slug' => 'teicoplanine-tec-30',
                'sku' => 'REACTIF-TEC30',
                'price' => 275.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Teicoplanine 30μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 38,
                'rating' => 4.6,
                'reviews_count' => 4,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'STREPTOMYCINE S-25',
                'slug' => 'streptomycine-s-25',
                'sku' => 'REACTIF-S25',
                'price' => 185.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Streptomycine 25μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 52,
                'rating' => 4.4,
                'reviews_count' => 5,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'SPIRAMYCINE SP-100',
                'slug' => 'spiramycine-sp-100',
                'sku' => 'REACTIF-SP100',
                'price' => 205.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Spiramycine 100μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 44,
                'rating' => 4.5,
                'reviews_count' => 4,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'RIFAMPINE(RIFAMPICINE)RA-5',
                'slug' => 'rifampinerifampicinera-5',
                'sku' => 'REACTIF-RA5',
                'price' => 215.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Rifampicine 5μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 47,
                'rating' => 4.5,
                'reviews_count' => 4,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'RIFAMPINE (RIFAMPICINE) RA-30',
                'slug' => 'rifampine-rifampicine-ra-30',
                'sku' => 'REACTIF-RA30',
                'price' => 235.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Rifampicine 30μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 41,
                'rating' => 4.6,
                'reviews_count' => 3,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'PRISTINAMYCIN PT-15',
                'slug' => 'pristinamycin-pt-15',
                'sku' => 'REACTIF-PT15',
                'price' => 245.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Pristinamycine 15μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 36,
                'rating' => 4.5,
                'reviews_count' => 3,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'PIPERACILLINE/TAZOBACTAM TPZ-36',
                'slug' => 'piperacillinetazobactam-tpz-36',
                'sku' => 'REACTIF-TPZ36',
                'price' => 295.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Pipéracilline/Tazobactam 36μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 32,
                'rating' => 4.7,
                'reviews_count' => 3,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'PIPERACILLINE PRL-30',
                'slug' => 'piperacilline-prl-30',
                'sku' => 'REACTIF-PRL30',
                'price' => 255.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Pipéracilline 30μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 39,
                'rating' => 4.5,
                'reviews_count' => 3,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'PENICILINE P-10',
                'slug' => 'peniciline-p-10',
                'sku' => 'REACTIF-P10',
                'price' => 165.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Pénicilline 10μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 58,
                'rating' => 4.3,
                'reviews_count' => 6,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'OXACILLINE OX-1',
                'slug' => 'oxacilline-ox-1',
                'sku' => 'REACTIF-OX1',
                'price' => 175.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Oxacilline 1μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 54,
                'rating' => 4.4,
                'reviews_count' => 5,
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'OFLOXACIN OFX-5',
                'slug' => 'ofloxacin-ofx-5',
                'sku' => 'REACTIF-OFX5',
                'price' => 195.00,
                'original_price' => null,
                'category_slug' => 'disques-dantibiotiques',
                'brand' => 'Bioelab',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Disque d\'antibiotique Ofloxacine 5μg pour tests de sensibilité.',
                'features' => null,
                'attributes' => null,
                'stock' => 46,
                'rating' => 4.4,
                'reviews_count' => 4,
                'badge' => null,
                'featured' => false,
            ],

            // EQUIPEMENTS DE LABORATOIRE
            [
                'name' => 'Thermomètre (-10 à 100°C)',
                'slug' => 'thermometre-10-a-100',
                'sku' => 'EQUIP-THERMO-001',
                'price' => 320.00,
                'original_price' => null,
                'category_slug' => 'equipements-de-laboratoire',
                'brand' => 'Labware',
                'image' => 'https://teclab.ma/storage/products/divers/gemini-generated-image-mt5nx2mt5nx2mt5n-300x300.jpg',
                'description' => 'Thermomètre de laboratoire précis de -10°C à 100°C. Idéal pour toutes vos mesures de température.',
                'features' => null,
                'attributes' => null,
                'stock' => 25,
                'rating' => 4.3,
                'reviews_count' => 8,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Minuteur digital',
                'slug' => 'minuteur-digital',
                'sku' => 'EQUIP-MINUTEUR-DIG-001',
                'price' => 180.00,
                'original_price' => null,
                'category_slug' => 'equipements-de-laboratoire',
                'brand' => 'Labware',
                'image' => 'https://teclab.ma/storage/products/divers/gemini-generated-image-1yevup1yevup1yev-300x300.jpg',
                'description' => 'Minuteur digital avec alarme sonore. Mémoire de plusieurs temps. Idéal pour le laboratoire.',
                'features' => null,
                'attributes' => null,
                'stock' => 40,
                'rating' => 4.6,
                'reviews_count' => 12,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Minuteur analogique',
                'slug' => 'minuteur-analogique',
                'sku' => 'EQUIP-MINUTEUR-ANA-001',
                'price' => 120.00,
                'original_price' => null,
                'category_slug' => 'equipements-de-laboratoire',
                'brand' => 'Labware',
                'image' => 'https://teclab.ma/storage/products/divers/gemini-generated-image-v1km8lv1km8lv1km-300x300.jpg',
                'description' => 'Minuteur analogique mécanique, simple et fiable. Sans piles, idéal pour une utilisation continue.',
                'features' => null,
                'attributes' => null,
                'stock' => 35,
                'rating' => 4.2,
                'reviews_count' => 6,
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Bec Benzène',
                'slug' => 'bec-benzene',
                'sku' => 'EQUIP-BEC-001',
                'price' => 280.00,
                'original_price' => null,
                'category_slug' => 'equipements-de-laboratoire',
                'brand' => 'Labware',
                'image' => 'https://teclab.ma/storage/products/anses/gemini-generated-image-xblqx7xblqx7xblq-300x300.jpg',
                'description' => 'Bec Benzène pour travaux de stérilisation. Idéal pour la stérilisation des anses de platine.',
                'features' => null,
                'attributes' => null,
                'stock' => 18,
                'rating' => 4.5,
                'reviews_count' => 5,
                'badge' => 'Hot',
                'featured' => false,
            ],
        ];

        foreach ($products as $productData) {
            $categorySlug = $productData['category_slug'];
            unset($productData['category_slug']);
            
            $category = $categories[$categorySlug] ?? null;
            
            if ($category) {
                $productData['category_id'] = $category->id;
                Product::create($productData);
            } else {
                $this->command->warn("Category not found for slug: {$categorySlug}");
            }
        }

        $this->command->info('Products seeded successfully!');
    }
}