<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all categories
        $categories = Category::all();
        
        if ($categories->isEmpty()) {
            $this->command->error('No categories found. Please run CategorySeeder first.');
            return;
        }

        $products = [
            // TUBES DE PRELEVEMENT Category (38)
            [
                'name' => 'Tube Sous Vide SEC (Sans Additifs) 4ml En Plastique',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-739',
                'price' => 95.00,
                'original_price' => 100.00,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/gemini-generated-image-34dzbm34dzbm34dz-300x300.jpg',
                'description' => 'Tube sous vide SEC (sans additifs) 4ml en plastique pour prélèvement sanguin.',
                'features' => json_encode(['Volume: 4ml', 'Sans additifs', 'Plastique']),
                'attributes' => json_encode(['type' => 'SEC', 'volume' => '4ml', 'material' => 'Plastique']),
                'stock' => rand(10, 50),
                'rating' => 4.5,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Tube PRP GEL+NC1:9',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-186',
                'price' => 140.00,
                'original_price' => 150.00,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/whatsapp-image-2026-01-21-at-140953-photoroom-300x300.png',
                'description' => 'Tube PRP avec gel séparateur pour plasma riche en plaquettes.',
                'features' => json_encode(['Avec gel', 'Rapport 1:9', 'Pour PRP']),
                'attributes' => json_encode(['type' => 'PRP', 'gel' => 'Oui', 'ratio' => '1:9']),
                'stock' => rand(10, 50),
                'rating' => 4.8,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => true,
            ],
            [
                'name' => 'Tube Sous Vide ESR 1,6ml en Verre',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-178',
                'price' => 800.00,
                'original_price' => null,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/gemini-generated-image-b4on7wb4on7wb4on-300x300.jpg',
                'description' => 'Tube sous vide pour vitesse de sédimentation (ESR) en verre.',
                'features' => json_encode(['Volume: 1.6ml', 'Pour ESR', 'Verre']),
                'attributes' => json_encode(['type' => 'ESR', 'volume' => '1.6ml', 'material' => 'Verre']),
                'stock' => rand(10, 50),
                'rating' => 4.6,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide Fluoré De Potassium En Plastique',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-175',
                'price' => 120.00,
                'original_price' => null,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-202209012048532-600x-300x300.jpg',
                'description' => 'Tube sous vide avec fluorure de potassium pour la glycolyse.',
                'features' => json_encode(['Fluorure de potassium', 'Pour glucose', 'Plastique']),
                'attributes' => json_encode(['type' => 'Fluoré', 'additif' => 'Fluorure de potassium', 'material' => 'Plastique']),
                'stock' => rand(10, 50),
                'rating' => 4.7,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide avec Gel Séparateur En Plastique',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-173',
                'price' => 130.00,
                'original_price' => null,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-202209012048541-2a25-300x300.jpg',
                'description' => 'Tube sous vide avec gel séparateur pour sérum.',
                'features' => json_encode(['Avec gel séparateur', 'Pour sérum', 'Plastique']),
                'attributes' => json_encode(['type' => 'Gel', 'gel' => 'Séparateur', 'material' => 'Plastique']),
                'stock' => rand(10, 50),
                'rating' => 4.5,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => true,
            ],
            [
                'name' => 'Tube Sous Vide Héparine En Plastique',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-169',
                'price' => 110.00,
                'original_price' => null,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-20220901204853-1200x-300x300.jpg',
                'description' => 'Tube sous vide avec héparine pour plasma.',
                'features' => json_encode(['Héparine', 'Pour plasma', 'Plastique']),
                'attributes' => json_encode(['type' => 'Héparine', 'additif' => 'Héparine', 'material' => 'Plastique']),
                'stock' => rand(10, 50),
                'rating' => 4.4,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide Citrate pour V.S En Plastique',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-166',
                'price' => 115.00,
                'original_price' => null,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/whatsapp-image-2026-01-21-at-140429-1-photoroom-300x300.png',
                'description' => 'Tube sous vide avec citrate pour vitesse de sédimentation.',
                'features' => json_encode(['Citrate', 'Pour VS', 'Plastique']),
                'attributes' => json_encode(['type' => 'Citrate VS', 'additif' => 'Citrate', 'material' => 'Plastique']),
                'stock' => rand(10, 50),
                'rating' => 4.5,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide Citrate pour Coagulation En Plastique',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-162',
                'price' => 125.00,
                'original_price' => null,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-20220901204854-1024x-300x300.jpg',
                'description' => 'Tube sous vide avec citrate pour tests de coagulation.',
                'features' => json_encode(['Citrate', 'Pour coagulation', 'Plastique']),
                'attributes' => json_encode(['type' => 'Citrate Coagulation', 'additif' => 'Citrate', 'material' => 'Plastique']),
                'stock' => rand(10, 50),
                'rating' => 4.6,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => false,
            ],
            [
                'name' => 'Tube Sous Vide EDTA En Plastique',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-157',
                'price' => 105.00,
                'original_price' => null,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/65309-home-default-300x300.jpg',
                'description' => 'Tube sous vide avec EDTA pour hématologie.',
                'features' => json_encode(['EDTA', 'Pour hématologie', 'Plastique']),
                'attributes' => json_encode(['type' => 'EDTA', 'additif' => 'EDTA', 'material' => 'Plastique']),
                'stock' => rand(10, 50),
                'rating' => 4.7,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => true,
            ],
            [
                'name' => 'Tube Sous Vide SEC (Avec Activateur) En Plastique',
                'category' => 'TUBES DE PRELEVEMENT',
                'sku' => 'SKU-153',
                'price' => 118.00,
                'original_price' => null,
                'brand' => 'VACULAB',
                'image' => 'https://teclab.ma/storage/products/tube-sous-vide/wechatimage-202209012048531-1200x-300x300.webp',
                'description' => 'Tube sous vide SEC avec activateur de coagulation.',
                'features' => json_encode(['Avec activateur', 'Pour sérum', 'Plastique']),
                'attributes' => json_encode(['type' => 'SEC avec activateur', 'additif' => 'Activateur', 'material' => 'Plastique']),
                'stock' => rand(10, 50),
                'rating' => 4.5,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => false,
            ],

            // AIGUILLES ET ACCESSOIRES Category (40)
            [
                'name' => 'VANCOMYCINE VA-5',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-958',
                'price' => 450.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Vancomycine VA-5 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'VA-5']),
                'stock' => rand(10, 50),
                'rating' => 4.3,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'VANCOMYCINE VA-30',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-956',
                'price' => 550.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Vancomycine VA-30 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'VA-30']),
                'stock' => rand(10, 50),
                'rating' => 4.4,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'TOBRAMYCINE TOB-10',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-954',
                'price' => 420.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Tobramycine TOB-10 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'TOB-10']),
                'stock' => rand(10, 50),
                'rating' => 4.2,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'TICARCILLINE TIC-75',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-952',
                'price' => 480.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Ticarcilline TIC-75 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'TIC-75']),
                'stock' => rand(10, 50),
                'rating' => 4.3,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'TETRACYCLINE TE-30',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-950',
                'price' => 390.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Tetracycline TE-30 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'TE-30']),
                'stock' => rand(10, 50),
                'rating' => 4.1,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'TEICOPLANINE TEC-30',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-948',
                'price' => 520.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Teicoplanine TEC-30 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'TEC-30']),
                'stock' => rand(10, 50),
                'rating' => 4.5,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'STREPTOMYCINE S-25',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-946',
                'price' => 410.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Streptomycine S-25 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'S-25']),
                'stock' => rand(10, 50),
                'rating' => 4.2,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'SPIRAMYCINE SP-100',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-944',
                'price' => 580.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Spiramycine SP-100 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'SP-100']),
                'stock' => rand(10, 50),
                'rating' => 4.4,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'RIFAMPINE(RIFAMPICINE)RA-5',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-942',
                'price' => 460.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Rifampine RA-5 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'RA-5']),
                'stock' => rand(10, 50),
                'rating' => 4.3,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'RIFAMPINE (RIFAMPICINE) RA-30',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-940',
                'price' => 560.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Rifampine RA-30 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'RA-30']),
                'stock' => rand(10, 50),
                'rating' => 4.4,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'PRISTINAMYCIN PT-15',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-938',
                'price' => 530.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Pristinamycin PT-15 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'PT-15']),
                'stock' => rand(10, 50),
                'rating' => 4.2,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'PIPERACILLINE/TAZOBACTAM TPZ-36',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-936',
                'price' => 680.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Piperacilline/Tazobactam TPZ-36 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'TPZ-36']),
                'stock' => rand(10, 50),
                'rating' => 4.6,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'PIPERACILLINE PRL-30',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-934',
                'price' => 490.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Piperacilline PRL-30 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'PRL-30']),
                'stock' => rand(10, 50),
                'rating' => 4.3,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'PENICILINE P-10',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-932',
                'price' => 380.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Peniciline P-10 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'P-10']),
                'stock' => rand(10, 50),
                'rating' => 4.0,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'OXACILLINE OX-1',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-930',
                'price' => 420.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Oxacilline OX-1 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'OX-1']),
                'stock' => rand(10, 50),
                'rating' => 4.1,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'OFLOXACIN OFX-5',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-928',
                'price' => 440.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Ofloxacin OFX-5 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'OFX-5']),
                'stock' => rand(10, 50),
                'rating' => 4.2,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'NORFLOXACIN NOR-10',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-926',
                'price' => 430.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Norfloxacin NOR-10 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'NOR-10']),
                'stock' => rand(10, 50),
                'rating' => 4.1,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'NITROFURANTOIN F300',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-924',
                'price' => 470.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Nitrofurantoin F300 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'F300']),
                'stock' => rand(10, 50),
                'rating' => 4.3,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'NITROFURANTOIN F100',
                'category' => 'AIGUILLES ET ACCESSOIRES',
                'sku' => 'SKU-922',
                'price' => 380.00,
                'original_price' => null,
                'brand' => 'BIOKAR',
                'image' => 'https://teclab.ma/storage/whatsapp-image-2026-02-03-at-104338-300x300.jpeg',
                'description' => 'Nitrofurantoin F100 pour tests de sensibilité.',
                'features' => json_encode(['Antibiotique', 'Pour tests']),
                'attributes' => json_encode(['type' => 'Antibiotique', 'code' => 'F100']),
                'stock' => rand(10, 50),
                'rating' => 4.0,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],

            // CONSOMMABLES DE LABORATOIRE Category (41)
            [
                'name' => 'Support Mobile pour Détecteur De Veines',
                'category' => 'CONSOMMABLES DE LABORATOIRE',
                'sku' => 'SKU-984',
                'price' => 2500.00,
                'original_price' => 3000.00,
                'brand' => 'QUALMEDI',
                'image' => 'https://teclab.ma/storage/chatgpt-image-mar-3-2026-12-57-09-am-300x300.png',
                'description' => 'Support mobile pour détecteur de veines, facile à déplacer.',
                'features' => json_encode(['Mobile', 'Pour détecteur de veines']),
                'attributes' => json_encode(['type' => 'Support', 'usage' => 'Détecteur de veines']),
                'stock' => rand(10, 50),
                'rating' => 4.5,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Support de table Pour Détecteur De Veines',
                'category' => 'CONSOMMABLES DE LABORATOIRE',
                'sku' => 'SKU-983',
                'price' => 1800.00,
                'original_price' => null,
                'brand' => 'QUALMEDI',
                'image' => 'https://teclab.ma/storage/chatgpt-image-mar-3-2026-12-53-08-am-300x300.png',
                'description' => 'Support de table pour détecteur de veines, stable et compact.',
                'features' => json_encode(['Table', 'Pour détecteur de veines']),
                'attributes' => json_encode(['type' => 'Support', 'usage' => 'Détecteur de veines']),
                'stock' => rand(10, 50),
                'rating' => 4.3,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Sparadrap adulte',
                'category' => 'CONSOMMABLES DE LABORATOIRE',
                'sku' => 'SKU-981',
                'price' => 150.00,
                'original_price' => 200.00,
                'brand' => 'CURE-AID',
                'image' => 'https://teclab.ma/storage/products/chatgpt-image-feb-26-2026-02-01-23-pm-300x300.png',
                'description' => 'Sparadrap adulte pour fixation de pansements.',
                'features' => json_encode(['Adulte', 'Pour fixation']),
                'attributes' => json_encode(['type' => 'Sparadrap', 'usage' => 'Adulte']),
                'stock' => rand(10, 50),
                'rating' => 4.4,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => true,
            ],

            // REACTIFS DE LABORATOIRE Category (75)
            [
                'name' => 'RF LATEX',
                'category' => 'REACTIFS DE LABORATOIRE',
                'sku' => 'SKU-982',
                'price' => 1200.00,
                'original_price' => null,
                'brand' => 'HYCEL',
                'image' => 'https://teclab.ma/storage/chatgpt-image-mar-2-2026-11-37-47-am-300x300.png',
                'description' => 'Réactif RF Latex pour tests de facteur rhumatoïde.',
                'features' => json_encode(['Latex', 'Pour facteur rhumatoïde']),
                'attributes' => json_encode(['type' => 'Réactif', 'test' => 'RF']),
                'stock' => rand(10, 50),
                'rating' => 4.6,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => true,
            ],

            // ANALYSEURS DE LABORATOIRE Category (95)
            [
                'name' => 'Analyseur de biochimie BT-330',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-979',
                'price' => 45000.00,
                'original_price' => null,
                'brand' => 'BIOELAB',
                'image' => 'https://teclab.ma/storage/products/machine/chatgpt-image-feb-14-2026-12-09-48-pm-300x300.png',
                'description' => 'Analyseur de biochimie BT-330 pour tests cliniques.',
                'features' => json_encode(['Biochimie', 'Automatisé']),
                'attributes' => json_encode(['type' => 'Analyseur', 'domaine' => 'Biochimie']),
                'stock' => rand(1, 5),
                'rating' => 4.8,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => true,
            ],
            [
                'name' => 'Détecteur de veines QV-600',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-978',
                'price' => 12000.00,
                'original_price' => null,
                'brand' => 'QUALMEDI',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-xnllijxnllijxnll-300x300.png',
                'description' => 'Détecteur de veines QV-600 pour localisation facile des veines.',
                'features' => json_encode(['Détection veines', 'Portable']),
                'attributes' => json_encode(['type' => 'Détecteur', 'modèle' => 'QV-600']),
                'stock' => rand(1, 5),
                'rating' => 4.7,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Détecteur de veines QV-500',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-977',
                'price' => 9500.00,
                'original_price' => null,
                'brand' => 'QUALMEDI',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-8v45cb8v45cb8v45-300x300.png',
                'description' => 'Détecteur de veines QV-500 compact et efficace.',
                'features' => json_encode(['Détection veines', 'Compact']),
                'attributes' => json_encode(['type' => 'Détecteur', 'modèle' => 'QV-500']),
                'stock' => rand(1, 5),
                'rating' => 4.6,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'ANALYSEUR POUR VITESSE DE SEDIMENTATION SD-100',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-976',
                'price' => 28000.00,
                'original_price' => null,
                'brand' => 'SUCCEEDER',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-eim67heim67heim6-300x300.png',
                'description' => 'Analyseur pour vitesse de sédimentation SD-100.',
                'features' => json_encode(['Vitesse sédimentation', 'Automatisé']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'SD-100']),
                'stock' => rand(1, 5),
                'rating' => 4.5,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur de biochimie AS-380',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-974',
                'price' => 52000.00,
                'original_price' => null,
                'brand' => 'BIOELAB',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-h7hvj8h7hvj8h7hv-300x300.png',
                'description' => 'Analyseur de biochimie AS-380 haute performance.',
                'features' => json_encode(['Biochimie', 'Haute performance']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'AS-380']),
                'stock' => rand(1, 5),
                'rating' => 4.9,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur de biochimie AS-280',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-973',
                'price' => 38000.00,
                'original_price' => null,
                'brand' => 'BIOELAB',
                'image' => 'https://teclab.ma/storage/products/machine/3406e3f080cff89509270b153c5605af-300x300.png',
                'description' => 'Analyseur de biochimie AS-280 compact et fiable.',
                'features' => json_encode(['Biochimie', 'Compact']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'AS-280']),
                'stock' => rand(1, 5),
                'rating' => 4.7,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => true,
            ],
            [
                'name' => 'Analyseur d\'hématologie BH-5390',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-972',
                'price' => 65000.00,
                'original_price' => null,
                'brand' => 'URIT',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-yew64uyew64uyew6-300x300.png',
                'description' => 'Analyseur d\'hématologie BH-5390 5 différences.',
                'features' => json_encode(['Hématologie', '5 différences']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'BH-5390']),
                'stock' => rand(1, 5),
                'rating' => 4.8,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur d\'hématologie BH-5100',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-971',
                'price' => 48000.00,
                'original_price' => null,
                'brand' => 'URIT',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-ah1r0rah1r0rah1r-300x300.png',
                'description' => 'Analyseur d\'hématologie BH-5100 3 différences.',
                'features' => json_encode(['Hématologie', '3 différences']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'BH-5100']),
                'stock' => rand(1, 5),
                'rating' => 4.6,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur de coagulation entièrement automatisé SF-8100',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-970',
                'price' => 72000.00,
                'original_price' => null,
                'brand' => 'SUCCEEDER',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-vitlwbvitlwbvitl-300x300.png',
                'description' => 'Analyseur de coagulation entièrement automatisé SF-8100.',
                'features' => json_encode(['Coagulation', 'Automatisé']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'SF-8100']),
                'stock' => rand(1, 5),
                'rating' => 4.8,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur de coagulation semi-automatique SF-8050',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-969',
                'price' => 42000.00,
                'original_price' => null,
                'brand' => 'SUCCEEDER',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-pvfxm2pvfxm2pvfx-300x300.png',
                'description' => 'Analyseur de coagulation semi-automatique SF-8050.',
                'features' => json_encode(['Coagulation', 'Semi-automatique']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'SF-8050']),
                'stock' => rand(1, 5),
                'rating' => 4.5,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Semi automated coagulation analyzer SF-400',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-968',
                'price' => 35000.00,
                'original_price' => null,
                'brand' => 'SUCCEEDER',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-jmxae8jmxae8jmxa-300x300.png',
                'description' => 'Analyseur de coagulation semi-automatique SF-400.',
                'features' => json_encode(['Coagulation', 'Semi-automatique']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'SF-400']),
                'stock' => rand(1, 5),
                'rating' => 4.4,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur d\'hémoglobine glyquée MQ-6000',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-967',
                'price' => 38000.00,
                'original_price' => null,
                'brand' => 'MEDCONN',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-hz7r96hz7r96hz7r-300x300.png',
                'description' => 'Analyseur d\'hémoglobine glyquée MQ-6000.',
                'features' => json_encode(['HbA1c', 'Automatisé']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'MQ-6000']),
                'stock' => rand(1, 5),
                'rating' => 4.7,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur d\'hémoglobine glyquée MQ-2000PT',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-966',
                'price' => 25000.00,
                'original_price' => null,
                'brand' => 'MEDCONN',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-uih99zuih99zuih9-300x300.png',
                'description' => 'Analyseur d\'hémoglobine glyquée MQ-2000PT portable.',
                'features' => json_encode(['HbA1c', 'Portable']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'MQ-2000PT']),
                'stock' => rand(1, 5),
                'rating' => 4.5,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur d\'hémoglobine glyquée MQ-3000',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-965',
                'price' => 32000.00,
                'original_price' => null,
                'brand' => 'MEDCONN',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-iqmn91iqmn91iqmn-300x300.png',
                'description' => 'Analyseur d\'hémoglobine glyquée MQ-3000.',
                'features' => json_encode(['HbA1c', 'Automatisé']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'MQ-3000']),
                'stock' => rand(1, 5),
                'rating' => 4.6,
                'reviews_count' => rand(3, 15),
                'badge' => 'Hot',
                'featured' => true,
            ],
            [
                'name' => 'Analyseur Hurricane Immunoassay System HIPRO',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-964',
                'price' => 85000.00,
                'original_price' => null,
                'brand' => 'HIPRO',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-82gnve82gnve82gn-300x300.png',
                'description' => 'Analyseur Hurricane Immunoassay System HIPRO.',
                'features' => json_encode(['Immunoassay', 'Automatisé']),
                'attributes' => json_encode(['type' => 'Analyseur', 'marque' => 'HIPRO']),
                'stock' => rand(1, 5),
                'rating' => 4.9,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur immunologique HP-AFS/A1 PLUS HIPRO',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-963',
                'price' => 58000.00,
                'original_price' => null,
                'brand' => 'HIPRO',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-8mjsuh8mjsuh8mjs-300x300.png',
                'description' => 'Analyseur immunologique HP-AFS/A1 PLUS HIPRO.',
                'features' => json_encode(['Immunoassay', 'Fluorescence']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'HP-AFS/A1 PLUS']),
                'stock' => rand(1, 5),
                'rating' => 4.7,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Analyseur de gaz du sang EG-i',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-962',
                'price' => 68000.00,
                'original_price' => null,
                'brand' => 'EAGLENOS',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-39ijah39ijah39ij-300x300.png',
                'description' => 'Analyseur de gaz du sang EG-i.',
                'features' => json_encode(['Gaz du sang', 'Électrolytes']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'EG-i']),
                'stock' => rand(1, 5),
                'rating' => 4.8,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Electrolyte Analyzer EAGLENOS (K+;Na+;Cl-;iCa2+;iMg2+) EG-P1',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-961',
                'price' => 45000.00,
                'original_price' => null,
                'brand' => 'EAGLENOS',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-552llq552llq552l-300x300.png',
                'description' => 'Analyseur d\'électrolytes EG-P1 (K+, Na+, Cl-, iCa2+, iMg2+).',
                'features' => json_encode(['Électrolytes', 'Automatisé']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'EG-P1']),
                'stock' => rand(1, 5),
                'rating' => 4.7,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],
            [
                'name' => 'Electrolyte Analyzer HY-LITE 300',
                'category' => 'ANALYSEURS DE LABORATOIRE',
                'sku' => 'SKU-960',
                'price' => 39000.00,
                'original_price' => null,
                'brand' => 'HYCEL',
                'image' => 'https://teclab.ma/storage/products/machine/gemini-generated-image-j8fijyj8fijyj8fi-300x300.png',
                'description' => 'Analyseur d\'électrolytes HY-LITE 300.',
                'features' => json_encode(['Électrolytes', 'Compact']),
                'attributes' => json_encode(['type' => 'Analyseur', 'modèle' => 'HY-LITE 300']),
                'stock' => rand(1, 5),
                'rating' => 4.6,
                'reviews_count' => rand(3, 15),
                'badge' => null,
                'featured' => false,
            ],

            // EQUIPEMENTS DE LABORATOIRE Category (116)
            // Note: No specific products found in this category in the HTML,
            // but it exists as a category. We'll leave it empty or you can add later.
        ];

        $this->command->info('Starting to seed ' . count($products) . ' products...');
        
        $successCount = 0;
        $skippedCount = 0;

        foreach ($products as $productData) {
            $category = $categories->where('name', $productData['category'])->first();
            
            if ($category) {
                try {
                    Product::updateOrCreate(
                        ['sku' => $productData['sku']],
                        [
                            'name' => $productData['name'],
                            'slug' => Str::slug($productData['name'] . '-' . $productData['sku']),
                            'sku' => $productData['sku'],
                            'price' => $productData['price'],
                            'original_price' => $productData['original_price'],
                            'category_id' => $category->id,
                            'brand' => $productData['brand'],
                            'image' => $productData['image'],
                            'description' => $productData['description'],
                            'features' => $productData['features'],
                            'attributes' => $productData['attributes'],
                            'stock' => $productData['stock'],
                            'rating' => $productData['rating'],
                            'reviews_count' => $productData['reviews_count'],
                            'badge' => $productData['badge'],
                            'featured' => $productData['featured'],
                        ]
                    );
                    $successCount++;
                } catch (\Exception $e) {
                    $this->command->error("Failed to create product {$productData['name']}: " . $e->getMessage());
                    $skippedCount++;
                }
            } else {
                $this->command->warn("Category '{$productData['category']}' not found for product '{$productData['name']}'");
                $skippedCount++;
            }
        }

        $this->command->info("=====================================");
        $this->command->info("✅ PRODUCTS SEEDED SUCCESSFULLY!");
        $this->command->info("=====================================");
        $this->command->info("📊 Total products attempted: " . count($products));
        $this->command->info("✅ Successfully created: {$successCount}");
        $this->command->info("⚠️ Skipped: {$skippedCount}");
        $this->command->info("=====================================");
    }
}
